# Generated by Django 5.2.17 on 2026-09-19 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Agency', 'verbose_name_plural': 'Agencies'},
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_admins',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_managers',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.AddField(
            model_name='organization',
            name='subscription_status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='denied_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='max_admins',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='user',
            name='max_users',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='user',
            name='reports_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('agency', 'Agency'), ('manager', 'Manager'), ('admin', 'Admin'), ('user', 'User'), ('supervisor', 'Supervisor'), ('agent', 'Agent')], default='agent', max_length=20),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=80)),
                ('object_type', models.CharField(blank=True, default='', max_length=80)),
                ('object_id', models.CharField(blank=True, default='', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_links', to='accounts.permission')),
            ],
            options={
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
