[procaller_user]
type=user
quiet=yes
announce_join_leave=no
dtmf_passthrough=yes
talk_detection_events=no
dsp_drop_silence=no

[procaller_bridge]
type=bridge
mixing_interval=10
internal_sample_rate=auto
video_mode=none
sound_only_person=silence/1
sound_only_one=silence/1
sound_join=silence/1
sound_leave=silence/1
