# Generated by Django 5.2.17 on 2026-09-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('paused', 'Paused'), ('incall', 'In Call'), ('ended', 'Ended')], default='ready', max_length=16)),
                ('room_id', models.CharField(max_length=64, unique=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('direction', models.CharField(choices=[('Outbound', 'Outbound'), ('Inbound', 'Inbound')], default='Outbound', max_length=16)),
                ('state', models.CharField(choices=[('initiating', 'Initiating'), ('ringing', 'Ringing'), ('connected', 'Connected'), ('on_hold', 'On Hold'), ('ended', 'Ended')], default='initiating', max_length=16)),
                ('outcome', models.CharField(blank=True, choices=[('Connected', 'Connected'), ('No Answer', 'No Answer'), ('Busy', 'Busy'), ('Failed', 'Failed'), ('Cancelled', 'Cancelled')], default='', max_length=20)),
                ('disposition', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('muted', models.BooleanField(default=False)),
                ('on_hold', models.BooleanField(default=False)),
                ('recording', models.BooleanField(default=False)),
                ('callerid_token', models.CharField(max_length=40, unique=True)),
                ('asterisk_channel', models.CharField(blank=True, default='', max_length=128)),
                ('media_mode', models.CharField(default='sandbox', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ringing_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='crm.contact')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telephony.agentsession')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
