# Generated by Django 5.2.1 on 2026-09-22 07:34

import telephony.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='recording_bytes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='call',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to=telephony.models.call_recording_upload_to),
        ),
        migrations.AddField(
            model_name='call',
            name='recording_mime',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
