# Generated by Django 5.2.1 on 2026-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_preview_autodial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodesession',
            name='dial_ratio',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='call',
            name='dial_batch',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
    ]
