# Generated by Django 5.2.17 on 2026-09-19 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_permission_alter_organization_options_and_more'),
        ('campaigns', '0002_campaign_admin_campaign_agency_and_more'),
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('preview', 'Preview'), ('importing', 'Importing'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('valid_rows', models.PositiveIntegerField(default=0)),
                ('invalid_rows', models.PositiveIntegerField(default=0)),
                ('duplicate_rows', models.PositiveIntegerField(default=0)),
                ('imported_rows', models.PositiveIntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='contact',
            name='assigned_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contact',
            name='call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contact',
            name='dnc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='lead_status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('calling', 'Calling'), ('connected', 'Connected'), ('not_connected', 'Not Connected'), ('busy', 'Busy'), ('no_answer', 'No Answer'), ('wrong_number', 'Wrong Number'), ('interested', 'Interested'), ('not_interested', 'Not Interested'), ('callback', 'Callback'), ('promise_to_pay', 'Promise To Pay'), ('paid', 'Paid'), ('completed', 'Completed'), ('dnc', 'DNC/Blocked')], db_index=True, default='new', max_length=32),
        ),
        migrations.AddField(
            model_name='contact',
            name='next_callback_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['agency', 'campaign', 'lead_status'], name='crm_contact_agency__3e4655_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['agency', 'phone'], name='crm_contact_agency__4a981c_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['owner', 'lead_status'], name='crm_contact_owner_i_fb3e8a_idx'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='agency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='campaigns.campaign'),
        ),
        migrations.AddField(
            model_name='importjob',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
