# Generated by Django 5.2.17 on 2026-09-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='running', max_length=20)),
                ('dial_method', models.CharField(choices=[('manual', 'Manual'), ('preview', 'Preview'), ('progressive', 'Progressive'), ('ratio', 'Ratio')], default='manual', max_length=20)),
                ('caller_id', models.CharField(blank=True, default='', max_length=32)),
                ('caller_id_name', models.CharField(blank=True, default='ProCaller', max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
