# Generated by Django 5.2.17 on 2026-09-19 12:56

import campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_admin_campaign_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='hold_audio',
            field=models.FileField(blank=True, null=True, upload_to=campaigns.models.hold_audio_upload_to),
        ),
    ]
