# Generated by Django 5.2.1 on 2026-09-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_hold_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='code',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='campaign',
            name='wrap_up_seconds',
            field=models.PositiveIntegerField(default=30),
        ),
    ]
