# Generated by Django 5.2.1 on 2026-09-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_preview_autodial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='dial_ratio',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
