ROLE_PERMISSIONS = {
    "super_admin": [
        "create_agency",
        "manage_agency",
        "create_manager",
        "manage_manager",
        "create_admin",
        "manage_admin",
        "create_user",
        "manage_user",
        "create_campaign",
        "edit_campaign",
        "delete_campaign",
        "import_leads",
        "export_leads",
        "assign_leads",
        "manual_call",
        "preview_auto_dial",
        "view_call_logs",
        "view_reports",
        "manage_dispositions",
        "manage_calling_settings",
        "view_audit_logs",
    ],
    "agency": [
        "manage_agency",
        "create_manager",
        "manage_manager",
        "manage_admin",
        "manage_user",
        "create_campaign",
        "edit_campaign",
        "import_leads",
        "export_leads",
        "assign_leads",
        "manual_call",
        "preview_auto_dial",
        "view_call_logs",
        "view_reports",
        "view_audit_logs",
    ],
    "manager": [
        "create_admin",
        "manage_admin",
        "create_user",
        "manage_user",
        "create_campaign",
        "edit_campaign",
        "import_leads",
        "export_leads",
        "assign_leads",
        "manual_call",
        "preview_auto_dial",
        "view_call_logs",
        "view_reports",
    ],
    "admin": [
        "create_campaign",
        "edit_campaign",
        "import_leads",
        "export_leads",
        "assign_leads",
        "manual_call",
        "preview_auto_dial",
        "view_call_logs",
        "view_reports",
        "manage_dispositions",
    ],
    "user": [
        "manual_call",
        "preview_auto_dial",
        "view_call_logs",
    ],
}

PERMISSION_LABELS = {
    "create_agency": "Create agencies",
    "manage_agency": "Manage agencies",
    "create_manager": "Create managers",
    "manage_manager": "Manage managers",
    "create_admin": "Create admins",
    "manage_admin": "Manage admins",
    "create_user": "Create users",
    "manage_user": "Manage users",
    "create_campaign": "Create campaigns",
    "edit_campaign": "Edit campaigns",
    "delete_campaign": "Delete campaigns",
    "import_leads": "Import leads",
    "export_leads": "Export leads",
    "assign_leads": "Assign leads",
    "manual_call": "Manual calling",
    "preview_auto_dial": "Preview auto dial",
    "view_call_logs": "View call logs",
    "view_reports": "View reports",
    "manage_dispositions": "Manage dispositions",
    "manage_calling_settings": "Manage calling settings",
    "view_audit_logs": "View audit logs",
}
